# Generated by Django 2.1.5 on 2019-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_profile_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
