# Generated by Django 2.1.5 on 2019-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_profile_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutor',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutor_gpa',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
