# Generated by Django 2.1.5 on 2019-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20190401_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
