# Generated by Django 2.1.5 on 2019-04-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_profile_profilepicture'),
        ('matching', '0003_profile_first_login'),
    ]

    operations = [
    ]
