# Generated by Django 2.1.5 on 2019-04-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20190401_1855'),
        ('matching', '0005_auto_20190404_1621'),
    ]

    operations = [
    ]
